### ISSUE TITLE
CP001: Missing SYCL memset capabilities

### ISSUE THREAD

**Issue by mehdi-goli** [codeplaysoftware/standards-proposals#14]
Adding memset to SYCL by using https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueFillBuffer.html

**Comment by Ruyk** [comment]
Good catch, we need to add some class of memset function that can be implemented then via the clEnqueuFillBuffer

**Comment by Ruyk** [comment]
Fixed in #15 , up for review

**Comment by Ruyk** [comment]
Merged.
