### ISSUE TITLE
CP013: Abrupt transition to Proposed Wording

### ISSUE THREAD

**Issue by fraggamuffin** [codeplaysoftware/standards-proposals#31]
I feel we do that switch rather fast without some overall high level design description. Or may be it is scattered through the Proposed Wording.

**Comment by fraggamuffin** [comment]
This need not be addressed in this revision.

**Comment by AerialMantis** [comment]
So I did the proposed wording first and then added the overview section to describe it afterwards as that required some refactoring to move the straw polls from the last revision to the proposal of this revision. I think you saw it at the point before I added the overview section.

**Comment by Ruyk** [comment]
This can be closed now, as the paper has evolved and contains a fairly large introduction and description.
