### ISSUE TITLE
CP013: Work on placing work close to execution

### ISSUE THREAD

**Issue by fraggamuffin** [codeplaysoftware/standards-proposals#32]
I didn't find that part in the paper, are we not posting that part for review?

**Comment by fraggamuffin** [comment]
I finished the review and other then this issue it looks fine. Thanks.

**Comment by AerialMantis** [comment]
I added a section in the proposal overview which describes how this works in **Binding execution and allocation to resources**, and there's an example there, of binding allocation and work to an execution context.

**Comment by Ruyk** [comment]
Already addressed on the paper.
