### ISSUE TITLE
CP013: Provide clarity on the high-level interface

### ISSUE THREAD

**Issue by AerialMantis** [codeplaysoftware/standards-proposals#33]
There was feedback from Jacksonville that not all users would want to dive into the fine-grained work of querying a system's topology and manually binding resources, and that many users would instead want a higher-level descriptive interface which allows the implementation to decide how to allocate resources based on the user's requirements. There were concerns that we don't yet clearly present what a high-level interface for affinity would look like.

For Rapperswil we should provide clarity on the different levels of interface that we are proposing and their target users, and also on how we envision a high-level interface for affinity C++ to look like, preferably with examples.

**Comment by Ruyk** [comment]
This can be closed after https://github.com/codeplaysoftware/standards-proposals/pull/48 is merged.
