### ISSUE TITLE
CP013: Add way to retrieving current execution resource/context

### ISSUE THREAD

**Issue by AerialMantis** [codeplaysoftware/standards-proposals#34]
There was feedback from Jacksonville suggesting that we add a way to retrieve the execution resource or execution context of the current thread of execution.

**Comment by hcedwar** [comment]
In [P0737](https://github.com/kokkos/ISO-CPP-Papers/blob/master/P0737_ExecContext.rst) there was 

```
  extern const thread_execution_resource_t program_thread_execution_resource ;
  std::this_thread { 
    const thread_execution_resource_t & get_resource();
  }
```

For the global and local execution resource in which a `std::thread` could execute.

**Comment by AerialMantis** [comment]
Resolved by https://github.com/codeplaysoftware/standards-proposals/pull/44.
