### ISSUE TITLE
CP013: Stalled!

### ISSUE THREAD

**Issue by hcedwar** [codeplaysoftware/standards-proposals#55]
@AerialMantis (cc: @Ruyk)
We are stalled on [D0796r2](https://github.com/codeplaysoftware/standards-proposals/blob/master/affinity/cpp-20/d0796r2.md) waiting for you to weigh in with reviews on pull request #52 and others.

**Comment by AerialMantis** [comment]
We have finished reviewing #52. The blocker from our side is the removal of the explicit execution context interface, which we feel should be there, at least as a stub which can be defined later on.
